version: "3.9"
services:
  web:
    restart: always
    image: polariscope
    ports:
      - "84:80"
    depends_on:
      - db
    environment:
      - POLARI_USERNAME=costi
      - POLARI_PASSWORD=1234
      - DB_URL=jdbc:mysql://localhost:3306/polariscope?useSSL=false&serverTimezone=America/Los_Angeles&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      - DB_USER=root
      - DB_PASSWORD=1234
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ingrid-polariscope
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"